### ISSUE TITLE
SOCKS proxy support for applications configured to use Tor directly

### ISSUE THREAD

**Issue by brl** [subgraph/fw-daemon#7]
The firewall cannot see connections which are sent directly to the Tor proxy port.  To make it possible to also filter connections sent directly over the Tor proxy the fw-daemon could implement a socks proxy itself to chain in front of the Tor proxy.

**Comment by david415** [comment]
my sloppy work-in-progress is here https://github.com/david415/fw-daemon/tree/7.add_SOCKS_proxy_chain.0

i'll fix this later when my brain reboots. should be simple.

**Comment by david415** [comment]
OK. the unit tests for the SOCKS proxy chain work now. (we can squash sloppy commit history later)

Next we need to decide how to specify the listener addr and tor SOCKS addr... either via CLI or configuration file i suppose. Any suggestions?

please code review and i will fix it up

**Comment by david415** [comment]
Should the SOCKS proxy chain only handle connect requests or should it handle resolv and PTR resolv commands as well? If so then should firewall policy be applied to resolv commands?

It seems to me that the user denies a fw-daemon dialog box prompted SOCKS chained to tor connection then it should cause the socks chain daemon to fail the handshake. So from the client's perspective the socks proxy server fails to connect to it's target host. Sound appropriate? Otherwise we can silently drop the socks connection. ;-p

**Comment by david415** [comment]
I've switched to a new dev branch that uses my latest procsnitch interface:
https://github.com/david415/fw-daemon/tree/7.add_SOCKS_proxy_chain.1

I need to get the dbus prompter thingy to work with this socks proxy chain...
